go:
  - master


notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f)
  - go get github.com/gorilla/websocket
  - go get github.com/golang/lint/golint

script:
  - test -z $(gofmt -s -l $GO_FILES)  # check if files are gofmt'ed (https://golang.org/cmd/gofmt/)
  - go vet ./...                      # go vet all the files        (https://golang.org/cmd/vet/)
  - golint -set_exit_status ./...     # check coding style          (https://github.com/golang/lint)